### ISSUE TITLE
File and Printer Sharing Script

### ISSUE THREAD

**Issue by jasonhaymond** [davidhaymond/ProvisioningTools#3]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Include a built-in script to enable file and printer sharing for private and domain level networks.

**Comment by davidhaymond** [comment]
This is done by enabling a group of firewall rules. It might be worth generalizing to support enabling or disabling any group of firewall rules for Private, Domain, and/or Public.

**Comment by davidhaymond** [comment]
It is now possible to add arbitrary scripts to provisioning packages as of 758c92bee1a88701c75250574effbfed5c2bda96, so tasks like enabling file and printer sharing can be accomplished via script. I'll close this issue since I don't plan to implement features that aren't directly enabled by the provisioning packages themselves.
